[theme]
primaryColor = "#0072B2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F6F8"
textColor = "#172B3A"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
